services:
  api:
    build:
      context: ./webapi
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_SOURCE=paimon:paimon@tcp(db:3306)/genshindb?parseTime=true
    volumes:
      - ./webapi:/app
  db:
    image: mysql:8.0
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: genshindb
      MYSQL_USER: paimon
      MYSQL_PASSWORD: paimon1234
      MYSQL_ROOT_PASSWORD: paimon1234
      TZ: Asia/Tokyo
    volumes:
      - mysql:/var/lib/mysql
      - ./webapi/sql:/docker-entrypoint-initdb.d
      - ./webapi/sql/my.cnf:/etc/mysql/conf.d/my.cnf
volumes:
  mysql: